### PR TITLE
Add budget-alignment namespace to Sector codelist

### PR DESCRIPTION
**Pull request by andylolz**
An [IATI discuss post](https://discuss.iatistandard.org/t/mapping-budget-identifiers-and-dac-sectors/1322/2) from @markbrough included the following suggestion:

> perhaps this is something @IATI-techteam could consider adding to the [`Sector`](http://iatistandard.org/codelists/sector/) codelist to make clear which codes are compatible with budget alignment and which are not?

This pull request is the first step to doing that, by adding budget alignment information to the Sector codelist via a custom namespace.

Once this is merged, this could be added to [the Sector codelist page](http://iatistandard.org/codelists/Sector/#codes) on iatistandard.org.

---

One thing to mention… The codelist schema only allows for custom namespace elements inside of narrative elements. This is \*a bit odd\*. So I’ve added these inside the `name/narrative`, but I’d suggest amending the codelist.xsd to allow for custom namespace attributes on `codelist-item` / custom namespace elements inside `codelist-item`s.

### CODE REVIEW

**Comment by andylolz** [comment]
Hmm… This isn’t validating, so I guess I’m doing the custom namespace stuff wrong…

**Comment by andylolz** [comment]
> One thing to mention… The codelist schema only allows for custom namespace elements inside of narrative elements. This is *a bit odd*.

This is fixed now, so I’ve updated this PR accordingly.

**Comment by amy-silcock** [comment]
Thanks @andylolz for your work on this. At this time we're not going to be making these changes to the sector codelist. The guidance is only relevant for certain users and the mapping is not controlled by the OECD. 

Please do send PRs to update the [country budget alignment](https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.03/en/activity-standard/overview/country-budget-alignment.rst) guidance as needed and refer publishers/data users to this [guidance](http://reference.iatistandard.org/203/activity-standard/overview/country-budget-alignment/)

**Comment by andylolz** [comment]
> Please do send PRs to update the [country budget alignment](https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.03/en/activity-standard/overview/country-budget-alignment.rst) guidance as needed

Thanks! It’s fine I think. I reviewed it when it was written, so I’m happy with it.

**Pull request closed without merging**
