### PR TITLE
Adding SDG goals, targets, indicators to the TagVocabulary codelist

### PR DESCRIPTION
**Pull request by PetyaKangalova**
Proposal to add SDG goals, targets and indicators to the non-embedded codelist tag vocabulary: https://discuss.iatistandard.org/t/add-sdg-goals-and-targets-to-the-tagvocabulary-codelist/1562

 No objection so far.  Changes to be reviewed and merged by 4th of December.

### CODE REVIEW

**Comment by andylolz** [comment]
> No objection so far. Changes to be reviewed and merged by 4th of December.

The codelist management process is described on [the codelist management page](http://reference.iatistandard.org/203/codelists-guides/codelist-management/#updates-to-non-embedded-codelists):

> If a decision has been made to make a change to a non-embedded list the [IATI Standard discussion thread](http://discuss.iatistandard.org/c/iati-standard) **\*will be notified\*** (within 1 working day) about the change that is to be made and **\*the date that the change will take effect\*** (usually within 7 calendar days). The proposal will be **\*marked as ‘Planned’\*** on the support forum. At this point people have the right to disagree.

I’ve highlighted above all the bits that I don’t think happened here. In this sense, I don’t think the process has been adhered to.

@bill-anderson asked me to [provide […] evidence where the process for non-embedded codelists “doesn’t appear to be borne out in practice”](https://discuss.iatistandard.org/t/january-2018-dac-codelist-updates/1297/9). I think this is an example of that. I know it’s a very minor change, and I know this process might be a bit tiresome. But following an agreed process can help avoid limbo situations [like the one we now have on the tag vocab thread](https://discuss.iatistandard.org/t/add-sdg-goals-and-targets-to-the-tagvocabulary-codelist/1562).

Another example would be [the DAC CRS updates](https://discuss.iatistandard.org/t/january-2018-dac-codelist-updates/1297). There has been no objection to this update since it was proposed 7 months ago, but the changes remain unmerged. I understand there’s a plan to move to a more sustainable approach, but I think in the meantime, updates could and should continue to be made.

Sorry to go on about it.

**Comment by andylolz** [comment]
> No objection so far. Changes to be reviewed and merged by 4th of December.

The codelist management process is described on [the codelist management page](http://reference.iatistandard.org/203/codelists-guides/codelist-management/#updates-to-non-embedded-codelists):

> If a decision has been made to make a change to a non-embedded list the [IATI Standard discussion thread](http://discuss.iatistandard.org/c/iati-standard) **\*will be notified\*** (within 1 working day) about the change that is to be made and **\*the date that the change will take effect\*** (usually within 7 calendar days). The proposal will be **\*marked as ‘Planned’\*** on the support forum. At this point people have the right to disagree.

I’ve highlighted above all the bits that I don’t think happened here. In this sense, I don’t think the process has been adhered to.

I know this is a very minor change, and I know this process might be a bit tiresome. But following an agreed process can help avoid limbo situations [like the one we now have on the tag vocab thread](https://discuss.iatistandard.org/t/add-sdg-goals-and-targets-to-the-tagvocabulary-codelist/1562).

Another example would be [the DAC CRS updates](https://discuss.iatistandard.org/t/january-2018-dac-codelist-updates/1297). There has been no objection to this update since it was proposed 7 months ago, but the changes remain unmerged. I understand there’s a plan to move to a more sustainable approach, but I think in the meantime, updates could and should continue to be made.

Sorry to go on about it.

**Comment by PetyaKangalova** [comment]
@andylolz  It is indeed a mistake on my side - should have been clearer that merging and deployment for this change should not happen earlier than 4th of December (7 days after the response from the tech team on [IATI Discuss](https://discuss.iatistandard.org/t/planned-add-sdg-goals-and-targets-to-the-tagvocabulary-codelist/1562/2)). 

Because the pull request was merged earlier it was picked up in yesterday's deployment of the site. Hence the addition going live on the website. However, there is nothing irreversible. Given the current situation I would suggest that we wait for responses from the community until 4th of December on IATI discuss (as per the 7 day rule)  before making changes to this pull request again.  I hope that's okay?

I  will respond now on Discuss as well.

**Comment by andylolz** [comment]
Thanks @PetyaKangalova – that all sounds fine. Totally agree that the Tag Vocab change can be resolved in a satisfactory way, and agree with your proposed approach.

More generally, if you click through some of [the proposals on discuss](https://discuss.iatistandard.org/c/standard-management/non-embedded-codelist-amendments), you can see that a slightly different process is followed in each case. So even for those of us watching very closely, it’s not always easy to keep track. Sometimes there’s a response from the technical team outlining the process ([e.g. here](https://discuss.iatistandard.org/t/added-request-for-new-org-id-xi-iati-ochasdc/1378/2)). Sometimes there isn’t ([e.g. here](https://discuss.iatistandard.org/t/update-country-codelist-to-use-iso-3166-lower-case-short-names/1501)). Sometimes there’s a followup, and the subject line prefix is updated ([e.g. here](https://discuss.iatistandard.org/t/added-proposed-addition-to-the-indicator-vocabulary-codelist/946/8)). Sometimes there isn’t ([e.g. here](https://discuss.iatistandard.org/t/updates-to-the-iso-currency-codelist/1424)).

Just to mention again, there was no official response [on this DAC codelist update proposal](https://discuss.iatistandard.org/t/january-2018-dac-codelist-updates/1297) for six months. I’m still a bit unclear where it’s at – it sounds from @bill-anderson’s response that the proposal may have been rejected? If so, shouldn’t it be closed and marked as rejected?

**Comment by PetyaKangalova** [comment]
Proposal has been put on hold (as no consensus has been reached) so the pull request will need to be reverted and additions taken off until there is agreement within the community that SDGs should be added under TagVocabualy.

**Pull request merged**
