### PR TITLE
Updates description for Org-ID codelist 

### PR DESCRIPTION
**Pull request by stevieflow**
Trying again, to refresh branch

https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/252

https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/254

### CODE REVIEW

**Comment by andylolz** [comment]
Looks fine to me.

**Comment by andylolz** [comment]
This PR should be merged. #252 and #254 should be closed.

**Comment by amy-silcock** [comment]
Thanks @andylolz

**Comment by andylolz** [comment]
Thanks for getting this resolved! Apologies I didn’t spot the incomplete sentence – thanks for reviewing and fixing that!

**Pull request merged**
