### PR TITLE
Update org reg agency codelist from org-id.guide

### PR DESCRIPTION
**Pull request by andylolz**
This is a copy and paste [of the XML](http://org-id.guide/download.xml) from [org-id.guide](http://org-id.guide), to bring the OrganisationRegistrationAgency codelist in line with it.

Refs #235.

### CODE REVIEW

**Comment by andylolz** [comment]
Oh, nice – travis validates codelists against the schema! That is really cool.

I’ll go back to org-id.guide about the issue.

**Comment by andylolz** [comment]
As a test, in the three cases where multiple URLs are provided, I’ve tried selecting the first and ignoring the others. This fixes validation issues.

**Comment by andylolz** [comment]
Okay, codelist validates now. Thanks to @timgdavies for the necessary fixes.

**Comment by stevieflow** [comment]
@amy-silcock @PetyaKangalova @dalepotter are you able to review and merge this PR?  It would be great to do this soon, so that the two lists don't differ too much / too quickly

**Comment by andylolz** [comment]
Great – thanks all!

**Pull request merged**
