### PR TITLE
Add new SLE currency

### PR DESCRIPTION
**Pull request by andreaszenasidi**
Add new SLE currency code for Sierra Leone, issue nr: https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/358

### CODE REVIEW

**Review by nosvalds — APPROVED** [review]

**Comment by andylolz** [comment]
I don’t think `SLL` is withdrawn yet?

**Review by AudreyIATI — COMMENTED** [review]
All looks good to me.

**Comment by andreaszenasidi** [comment]
> I don’t think `SLL` is withdrawn yet?

@andylolz good point, I misunderstood the document. Will leave both currencies then.

**Review by AudreyIATI — COMMENTED** [review]
Looks good to me

**Review by nosvalds — APPROVED** [review]
Looks technically correct.

**Comment by nosvalds** [comment]
@AudreyIATI you need to approve to pass the check.

**Review by AudreyIATI — APPROVED** [review]

**Pull request merged**
