### PR TITLE
Re added withdrawn codes that were instead removed completely #313

### PR DESCRIPTION
**Pull request by samuele-mattiuzzo**

### CODE REVIEW

**Comment by andylolz** [comment]
This PR is identical to #302, except it doesn’t re-add withdrawn sector categories `230` and `920`.

Also, the commit message for d5f72d0 includes a bit more explanation, which may prove useful in the future.

Please consider reviewing and merging #302 in favour of this.

**Comment by andylolz** [comment]
Great to see this moving forward! But would you mind helping me understand why you didn't just merge #302? This PR seems to be identical to #302, except it doesn't re-add withdrawn sector categories `230` and `920`.

Thanks

**Comment by samuele-mattiuzzo** [comment]
> Great to see this moving forward! But would you mind helping me understand why you didn't proceed with #302? This PR seems to be identical to #302, except it doesn't re-add withdrawn sector categories `230` and `920`.
> 
> Thanks

Because I needed to understand it myself, and I could not figure out your commits due to my ineptitude around Codelists. Will look at yours as well tomorrow, thanks for pointing it out.

**Comment by andylolz** [comment]
Okay, thanks.

If I can help clarify anything at all, please do not hesitate to ask. The same applies to all of my open pull requests – I’m happy to provide further clarification if that’s useful.

**Comment by samuele-mattiuzzo** [comment]
@andylolz I realised I hadn't pushed that file for some reason, but yeah our PRs are identical, I think I just found it easier to go through the codes one by one and work out with the BA what was and wasn't removed and needed re adding

**Comment by andylolz** [comment]
Okay, great.

So since the PRs are identical, that’s equivalent to a passing review for #302, right?

**Comment by samuele-mattiuzzo** [comment]
Hacktober eh? :P

**Comment by andylolz** [comment]
Ha, no. #302 was created in July. Only PRs created in October count towards Hacktober.

**Comment by samuele-mattiuzzo** [comment]
yeah silly me 🤦‍♂ anyway, I'm just waiting for the 👍 from the BAs then I'll merge #302 in

**Comment by andylolz** [comment]
Great – thanks

**Pull request closed without merging**
