### PR TITLE
Pull organisation registration agency codelist from org-id.guide

### PR DESCRIPTION
**Pull request by andylolz**
The Organisation Registration Agency codelist description says:

> IATI periodically replicates the codelist of identifier sources from org-id.guide, to assist those accessing IATI documentation. However, it is advised that the most up-to-date source is the [org-id.guide project](http://org-id.guide/).

This pull request is a script to do this automatically, following the approach that currently exists in the repo for the FileType codelist (i.e. a get.sh script to download; a convert.py script to hammer into shape).

This also removes the FileType codelist updating, because the code is unused and incomplete.

Refs #235.

### CODE REVIEW

**Comment by PetyaKangalova** [comment]
Thanks @andylolz  I will leave for the devs to review the code. When we started the work with org-id.guide we agreed to replicate the list. However, as the list will continue growing and people will be more familiar with using org-id.guide, we need to revisit how we replicate the list and whether an external reference would be sufficient. @rory09 let's also add this issue for our next catch up for org-id.guide and talk about frequency at which we will be replicating the list.

**Comment by andylolz** [comment]
> Thanks @andylolz I will leave for the devs to review the code

You’re welcome! Great, thanks.

> whether an external reference would be sufficient

Makes sense. But I guess it would have to happen as part of a version upgrade, I think? So not any time soon.

> frequency at which we will be replicating the list

[The codelist management page](http://reference.iatistandard.org/203/codelists-guides/codelist-management/#special-cases) on the reference site says:

> #### Organisation Registration Agency
> 
> Because there is a need to add registration agencies quickly, so that people can do their work, and because we anticipate many additions that will not be of interest to most people, we will add values to this list without making announcements. Values to be added will be agreed at the weekly team meeting.

**Comment by andylolz** [comment]
Also very relevant is @stevieflow’s ticket on the org-id repo here: org-id/register#219

**Comment by samuele-mattiuzzo** [comment]
@andylolz are we not using/pulling FileFormat at all? should it not stay? if it's not used I don't mind killing it, but was wondering if maybe we wanted to keep both instead?

just asking because of lack of historical context, as usual :D

**Comment by andylolz** [comment]
> are we not using/pulling FileFormat at all? should it not stay?

According to the git history, it was last updated in #154, by me.

If you want to keep it, I’ll modify this PR to re-add it.

You’re best off discussing with @PetyaKangalova or @amy-silcock, or whoever is in charge of keeping replicated codelists up-to-date (I don’t know who that is).

**Comment by andylolz** [comment]
Btw I found one more post from an org-id person confused that OrganisationRegistrationAgency isn’t kept in sync with source: https://github.com/andylolz/org-id-finder/issues/6#issuecomment-363868555

**Pull request merged**
